force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Created for N26 Salesforce Case Study</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legal_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Create for N26 Salesforce Case Study</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External Id. Salesforce Case Study for N26</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <description>This object will contain all the information about the services provided.
Salesforce Case Study for N26</description>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Charge__c/Service_Charge__c.object-meta.xml
<CustomObject>
    <description>Junction Object for keeping the pricing details of service and product.
Salesforce Case Study for N26</description>
    <label>Service Charge</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Charge__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>Cost/Price of the service</description>
    <label>Cost</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service_Charge__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Charge__c/fields/Has_Percent_Cost__c.field-meta.xml
<CustomField>
    <fullName>Has_Percent_Cost__c</fullName>
    <formula>Percent_Cost__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Has Percent Cost</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Charge__c/fields/Is_Free_of_Cost__c.field-meta.xml
<CustomField>
    <fullName>Is_Free_of_Cost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Free of Cost</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Charge__c/fields/Percent_Cost__c.field-meta.xml
<CustomField>
    <fullName>Percent_Cost__c</fullName>
    <description>Cost in percentage as compared to other countries.</description>
    <label>Percent Cost</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Service_Charge__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Charges</relationshipLabel>
    <relationshipName>Service_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Charge__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Charges</relationshipLabel>
    <relationshipName>Service_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProductInfoRESTResource.cls
/**
 * @description       : 
 * @author            : Bilal Malik
 * @group             : 
 * @last modified on  : 06-14-2021
 * @last modified by  : Bilal Malik
 * Modifications Log 
 * Ver   Date         Author        Modification
 * 1.0   06-14-2021   Bilal Malik   Initial Version
**/
@RestResource(urlMapping='/ProductInfo/*')
global with sharing class ProductInfoRESTResource {
    
    /**
    * @description : GET request to get customer and product info by passing customer's UUID parameter in URL
    * @author Bilal Malik | 06-14-2021 
    * @return CustomerProductInfoWrapper JSON response
    **/
    @HttpGet
    global static CustomerProductInfoWrapper getProductInfoByUUID() {
        RestRequest request = RestContext.request;
        //Grab the UUID from the end of the URL
        String contactUUID = request.requestURI.substring(request.requestURI.lastIndexOf('/') + 1);
        system.debug('request.requestURI --> ' + request.requestURI);
        system.debug('contactUUID --> ' + contactUUID);
        CustomerProductInfoWrapper productInfoWrapper = createProductInfoResponse(contactUUID);
        return productInfoWrapper;
    }

    /**
    * @description : Method to process and create product services response for GET request
    * @author Bilal Malik | 06-14-2021 
    * @param contactUUID 
    * @return CustomerProductInfoWrapper 
    **/
    private static CustomerProductInfoWrapper createProductInfoResponse(String contactUUID){

        CustomerProductInfoWrapper productInfoWrapper = new CustomerProductInfoWrapper();
        CustomerProductInfoWrapper.Status requestStatus = new CustomerProductInfoWrapper.Status();
        requestStatus.message = 'success';
        requestStatus.code = 200;
        try {
            //if request doesn't have an Id parameter
            if(contactUUID == null || String.isEmpty(contactUUID)){
                requestStatus.message = 'Bad request. Customer UUID parameter is missing.';
                requestStatus.code = 400;
            }else{
                productInfoWrapper.uuid = contactUUID;                
                List<Contact> customers = [SELECT Id, Name, Product__c, Product__r.Name,
                                           Home_Country__c, Email, UUID__c  
                                           FROM Contact 
                                           WHERE UUID__c  =: contactUUID];
                
                //If no customer found against UUID
                if(customers.isEmpty()){
                    requestStatus.message = 'No customer found against this UUID.';
                }else{
                    productInfoWrapper.customer = customers[0];
                    if(customers[0].Product__c != null && customers[0].Home_Country__c != null){
                        productInfoWrapper.productName = customers[0].Product__r.Name;
                        productInfoWrapper.services = new List<Service_Charge__c>();
                        productInfoWrapper.services = [SELECT Id, Service__c, Service__r.Name, Product__c, Product__r.Name, 
                                                       Country__c, Cost__c, Percent_Cost__c, Is_Free_of_Cost__c,
                                                       Has_Percent_Cost__c, Currency_Code__c, Is_Active__c
                                                       FROM Service_Charge__c 
                                                       WHERE Product__c =: customers[0].Product__c 
                                                       AND Country__c =: customers[0].Home_Country__c
                                                       AND Is_Active__c = true];
                    }else{
                        //No products
                        requestStatus.message = 'This customer do not have any products.';
                    }
                }
            }

        } catch (Exception e) {
            //Internal server error
            requestStatus.message = e.getMessage();
            requestStatus.code = 500;
        }
        productInfoWrapper.status = requestStatus;
        return productInfoWrapper;
    }
}