force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Created for N26 Salesforce Case Study</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legal_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Create for N26 Salesforce Case Study</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <description>This object will contain all the information about the services provided.
Salesforce Case Study for N26</description>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Charge__c/Service_Charge__c.object-meta.xml
<CustomObject>
    <description>Junction Object for keeping the pricing details of service and product.
Salesforce Case Study for N26</description>
    <label>Service Charge</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Charge__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>Cost/Price of the service</description>
    <label>Cost</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service_Charge__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Charge__c/fields/Has_Percent_Cost__c.field-meta.xml
<CustomField>
    <fullName>Has_Percent_Cost__c</fullName>
    <formula>Percent_Cost__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Has Percent Cost</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Charge__c/fields/Is_Free_of_Cost__c.field-meta.xml
<CustomField>
    <fullName>Is_Free_of_Cost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Free of Cost</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Charge__c/fields/Percent_Cost__c.field-meta.xml
<CustomField>
    <fullName>Percent_Cost__c</fullName>
    <description>Cost in percentage as compared to other countries.</description>
    <label>Percent Cost</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Service_Charge__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Charges</relationshipLabel>
    <relationshipName>Service_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Charge__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Charges</relationshipLabel>
    <relationshipName>Service_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProductInfoController.cls
/**
 * @description       : Backend Apex controller class for "ProductInfoLWC" Lightning Web Component to show
 *                      the product information on the case page layout of the customer related to the case which is being viewed
 * @author            : Bilal Malik
 * @group             : 
 * @last modified on  : 06-14-2021
 * @last modified by  : Bilal Malik
 * Modifications Log 
 * Ver   Date         Author        Modification
 * 1.0   06-13-2021   Bilal Malik   Initial Version
**/
public with sharing class ProductInfoController {
    
    /**
    * @description : Method to get case record along with contact's fields
    * @author Bilal Malik | 06-14-2021 
    * @param caseId 
    * @return Case record
    **/
    @AuraEnabled(cacheable=true)
    public static Case getCaseInfo(Id caseId){
        Case caseObj;
        try {
            caseObj = [SELECT Id, ContactId, Contact.Home_Country__c,
                       Contact.Product__c,Contact.Product__r.name
                       FROM Case
                       WHERE Id =:caseId];

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return caseObj;
    }

    /**
    * @description : This method will return the active product information against country and product Id
    * @author Bilal Malik | 06-14-2021 
    * @param case object 
    * @return List<Service_Charge__c> 
    **/
    @AuraEnabled
    public static List<Service_Charge__c> getProductInfo(Case caseObj){
        List<Service_Charge__c> productCharges = new List<Service_Charge__c>();
        try {
            if(caseObj != null && caseObj.ContactId != null &&  caseObj.Contact.Home_Country__c != null && caseObj.Contact.Product__c != null){
                productCharges = [SELECT Id, Service__c, Service__r.Name, Product__c, Product__r.Name, Cost__c, Percent_Cost__c,
                                  Is_Free_of_Cost__c, Country__c, Has_Percent_Cost__c, Currency_Code__c
                                  FROM Service_Charge__c
                                  WHERE Product__c =: caseObj.Contact.Product__c
                                  AND Country__c =: caseObj.Contact.Home_Country__c
                                  AND Is_Active__c = True];
            }
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return productCharges;
    }
}