force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Created for N26 Salesforce Case Study</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legal_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Create for N26 Salesforce Case Study</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External Id. Salesforce Case Study for N26</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <description>This object will contain all the information about the services provided.
Salesforce Case Study for N26</description>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Charge__c/Service_Charge__c.object-meta.xml
<CustomObject>
    <description>Junction Object for keeping the pricing details of service and product.
Salesforce Case Study for N26</description>
    <label>Service Charge</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Charge__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>Cost/Price of the service</description>
    <label>Cost</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service_Charge__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Charge__c/fields/Is_Free_of_Cost__c.field-meta.xml
<CustomField>
    <fullName>Is_Free_of_Cost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Free of Cost</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Charge__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Charges</relationshipLabel>
    <relationshipName>Service_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Charge__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Charges</relationshipLabel>
    <relationshipName>Service_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProductInfoRESTResourceTest.cls
/**
 * @description       : 
 * @author            : Bilal Malik
 * @group             : 
 * @last modified on  : 06-14-2021
 * @last modified by  : Bilal Malik
 * Modifications Log 
 * Ver   Date         Author        Modification
 * 1.0   06-14-2021   Bilal Malik   Initial Version
**/
@isTest
public with sharing class ProductInfoRESTResourceTest {
    @testSetup
    private static void initailizeTestData () {
        Product2 prod = new Product2(Name = 'Black');
        insert prod;
        
        //Creating Services
        Service__c service1 =new Service__c(Name = 'Cost per Calendar Month');
        Service__c service2 =new Service__c(Name = 'ATM Fee in other currencies');
        Service__c service3 =new Service__c(Name = 'Card Replacement Cost');        
        
        insert new List<Service__c>{service1,service2, service3};
            
            Service_Charge__c serviceCharge1 = new Service_Charge__c(Product__c = prod.Id,
                                                                     Service__c = service1.Id,
                                                                     Cost__c = 99.26,
                                                                     Is_Free_of_Cost__c = false,
                                                                     Currency_Code__c = 'EUR',
                                                                     Country__c = 'DE',
                                                                     Is_Active__c = true);
        Service_Charge__c serviceCharge2 = new Service_Charge__c(Product__c = prod.Id,
                                                                 Service__c = service2.Id,
                                                                 Is_Free_of_Cost__c = true,
                                                                 Currency_Code__c = 'EUR',
                                                                 Country__c = 'DE',
                                                                 Is_Active__c = true);
        Service_Charge__c serviceCharge3 = new Service_Charge__c(Product__c = prod.Id,
                                                                 Service__c = service3.id,
                                                                 Cost__c = 3.0,
                                                                 Is_Free_of_Cost__c = false,
                                                                 Currency_Code__c = 'EUR',
                                                                 Country__c = 'DE',
                                                                 Is_Active__c = true);
        
        insert new List<Service_Charge__c>{serviceCharge1, serviceCharge2, serviceCharge3};
            
        Contact  con = new Contact(lastname = 'Test',
                                    email = 'testuser@mail.com',
                                    Product__c = prod.Id,
                                    UUID__c = '258200',
                                    Home_Country__c = 'DE');
        insert con;
        
        Case c = new Case(Subject = 'Test Case PI',
                          Status = 'New',
                          Origin = 'Email',
                          ContactId = con.Id);
        insert c;
        
    }
    private static testmethod void missingUUIDHttpGet() {
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/ProductInfo/'; 
        req.httpMethod = 'GET';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        CustomerProductInfoWrapper productInfoWrapper = ProductInfoRESTResource.getProductInfoByUUID();
        Test.stopTest();
        
        System.assertEquals('Bad request. Customer UUID parameter is missing.', productInfoWrapper.Status.message, 'Customer UUID Missing');
        System.assertEquals(400, productInfoWrapper.Status.code, 'Status code should be 400');
    }
    
    private static testmethod void noCustomerFoundHttpGet() {
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/ProductInfo/5564'; 
        req.httpMethod = 'GET';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        CustomerProductInfoWrapper productInfoWrapper = ProductInfoRESTResource.getProductInfoByUUID();
        Test.stopTest();
        
        System.assertEquals('No customer found against this UUID.', productInfoWrapper.Status.message, 'Customer Found');
        System.assertEquals(200, productInfoWrapper.Status.code, 'Status code should be 200');
    }
    private static testmethod void productInfoHttpGet() {
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/ProductInfo/258200'; 
        req.httpMethod = 'GET';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        CustomerProductInfoWrapper productInfoWrapper = ProductInfoRESTResource.getProductInfoByUUID();
        Test.stopTest();
        
        System.assertEquals('success', productInfoWrapper.Status.message, 'success');
        System.assertEquals(200, productInfoWrapper.Status.code, 'Status code should be 200');
        System.assertEquals('Black', productInfoWrapper.productName, 'Product Name should be Black for this customer');
        System.assertEquals(3, productInfoWrapper.services.size(), 'services should be 3');
    }

    private static testmethod void noProductInfoHttpGet() {

        Contact contactToUpdate = [SELECT Id, Product__c 
                                    FROM Contact 
                                    WHERE UUID__c = '258200'
                                    LIMIT 1];
        
        contactToUpdate.Product__c = null;
        update contactToUpdate;
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/ProductInfo/258200'; 
        req.httpMethod = 'GET';
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        CustomerProductInfoWrapper productInfoWrapper = ProductInfoRESTResource.getProductInfoByUUID();
        Test.stopTest();
        
        System.assertEquals('This customer do not have any products.', productInfoWrapper.Status.message, 'No product');
        System.assertEquals(200, productInfoWrapper.Status.code, 'Status code should be 200');
    }
}